### ISSUE TITLE
Lights On

### ISSUE THREAD

**Issue by DavidAlt** [DavidAlt/CIFKM#27]
What is it?  Metrics dashboard

How do I get access?  Submit a ticket to ________(GSC?)

URL:  https://lightson.cerner.com/home/

What can I use it for?
* physician productivity
* CDS overrides

What can it do that we AREN'T using it for?

Concerns
* "data integrity is questionable"
* "half of it is disabled"

**Comment by gmigs09** [comment]
Submit a ticket to get access. Physician productivity although data integrity is questionable. Half of it is disabled. Pretty charts though.

Joseph Migliuri, MD

**Comment by DavidAlt** [comment]
Moved to MHSG repo
